# DevTools & Hot Reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=400ms
spring.devtools.restart.quiet-period=200ms

# Templates & Caching
spring.thymeleaf.cache=false

